### ISSUE TITLE
Set least privilege permissions for GitHub Workflow tokens

### ISSUE THREAD

**Issue by gabibguti** [goatandsheep/rc#29]
# Proposal
Hello, I'm working on behalf of Google and the [Open Source Security Foundation][ossf] to help open-source projects improve their supply-chain security.

I see we are not setting minimum [permissions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) for the GitHub Workflows in this project. And how does that matter? Setting minimum permission is interesting to prevent attackers from using a compromised GITHUB_TOKEN with write access to push malicious code into the project. And how do we do that? By setting permissions on each workflow to read only, or the least access they need.

This is considered a security best practice and therefore helps improve the project's security posture.

Would you be interested in a PR to do this?

## Additional Context

Setting least privilege permissions is recommended by:
- [Scorecards](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions)
- [Step Security](https://github.com/step-security/secure-workflows)
- [GitHub](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token)

Let me know if you have any questions!

[ossf]: https://openssf.org/

**Comment by goatandsheep** [comment]
Hi @gabibguti sure I'm open to it
